require("nvim_config.plugins.follow-md-links")
require("nvim_config.plugins.luasnip")
require("nvim_config.plugins.marks")
require("nvim_config.plugins.mini")
require("nvim_config.plugins.neogit")
require("nvim_config.plugins.telescope")
require("nvim_config.plugins.treesitter-context")
require("nvim_config.plugins.treesitter")
require("nvim_config.plugins.terminal")
require("nvim_config.plugins.octo")

require("nvim_config.plugins.colourschemes.rose-pine")
